netConfiguration:
  receivingPort: 1339

registryConfiguration:
  type: "arreat.impl.registry.CacheRegistry"
  remotes:
    - key: "@remote01"
      displayName: "Remote 01"
      netAddress: "10.192.178.64"
      port: 9080
    - key: "@remote02"
      displayName: "Remote 02"
      netAddress: "10.192.179.121"
      port: 9080