netConfiguration:
  receivingPort: 1337

registryConfiguration:
  type: "arreat.core.registry.CacheRegistry"
  remotes:
    - name: "@remote01"
      displayName: "Remote 01"
      ip: "127.0.0.1"
      port: 9082
    - name: "@remote02"
      displayName: "Remote 02"
      ip: "127.0.0.1"
      port: 9080